name: untitled1
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.5.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  flutter_dotenv: ^5.0.2
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  file_picker: ^8.0.0
  url_launcher: ^6.2.0
  path_provider: ^2.1.0
  image_picker: ^1.0.0
  shared_preferences: ^2.5.4
  open_file: ^3.5.10
  connectivity_plus: ^7.1.0
  firebase_core: ^4.6.0
  firebase_messaging: ^16.1.3
  flutter_local_notifications: ^21.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/empoy_final_app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter:

  uses-material-design: true

  assets:
    - assets/Empoy.png
    - assets/EMPOY 3.png
    - assets/empoy_calendar.png
    - assets/empoy_search.png
    - assets/empoy_map_walking.png
    - assets/empoy_homescreen.png
    - assets/PESOLOGO.jpg
    - assets/testempoy.gif
    - assets/empoy_app_icon.png
    - assets/empoy_final_app_icon.png
    - assets/empoy_notif_application_received.png
    - assets/empoy_notif_interview.png
    - assets/empoy_notif_rejected.png
    - assets/empoy_notif_hired.png
    - assets/empoy_notif_shortlisted.png
    - assets/empoy_no_internetconnection.png
    - .env
