<?php

namespace Database\Seeders;

use App\Models\AuditLog;
use Illuminate\Database\Seeder;

class AuditLogSeeder extends Seeder
{
    public function run(): void
    {
        $logs = [
            [
                'user_type'  => 'App\Models\PesoEmployee',
                'user_id'    => 1,
                'user_name'  => 'Admin PESO',
                'role'       => 'Admin',
                'action'     => 'Logged In',
                'module'     => 'System',
                'detail'     => 'Admin PESO logged in',
                'ip_address' => '192.168.1.1',
                'created_at' => now()->subDays(1)->setTime(8, 0),
                'updated_at' => now()->subDays(1)->setTime(8, 0),
            ],
            [
                'user_type'  => 'App\Models\PesoEmployee',
                'user_id'    => 1,
                'user_name'  => 'Admin PESO',
                'role'       => 'Admin',
                'action'     => 'Created',
                'module'     => 'Users',
                'detail'     => 'Staff user Carlo Reyes created',
                'ip_address' => '192.168.1.1',
                'created_at' => now()->subDays(1)->setTime(9, 15),
                'updated_at' => now()->subDays(1)->setTime(9, 15),
            ],
            [
                'user_type'  => 'App\Models\PesoEmployee',
                'user_id'    => 1,
                'user_name'  => 'Admin PESO',
                'role'       => 'Admin',
                'action'     => 'Status Changed',
                'module'     => 'Employers',
                'detail'     => 'Employer Accenture Philippines verified',
                'ip_address' => '192.168.1.1',
                'created_at' => now()->subDays(1)->setTime(10, 30),
                'updated_at' => now()->subDays(1)->setTime(10, 30),
            ],
            [
                'user_type'  => 'App\Models\Employer',
                'user_id'    => 1,
                'user_name'  => 'Accenture Philippines',
                'role'       => 'Employer',
                'action'     => 'Logged In',
                'module'     => 'System',
                'detail'     => 'Employer Accenture Philippines logged in',
                'ip_address' => '192.168.1.50',
                'created_at' => now()->subDays(1)->setTime(11, 0),
                'updated_at' => now()->subDays(1)->setTime(11, 0),
            ],
            [
                'user_type'  => 'App\Models\Employer',
                'user_id'    => 1,
                'user_name'  => 'Accenture Philippines',
                'role'       => 'Employer',
                'action'     => 'Created',
                'module'     => 'Job Listings',
                'detail'     => "Job 'Software Developer' created",
                'ip_address' => '192.168.1.50',
                'created_at' => now()->subDays(1)->setTime(11, 20),
                'updated_at' => now()->subDays(1)->setTime(11, 20),
            ],
            [
                'user_type'  => 'App\Models\PesoEmployee',
                'user_id'    => 1,
                'user_name'  => 'Admin PESO',
                'role'       => 'Admin',
                'action'     => 'Created',
                'module'     => 'Events',
                'detail'     => "Event 'Santiago City Job Fair 2026' created",
                'ip_address' => '192.168.1.1',
                'created_at' => now()->subDays(2)->setTime(14, 0),
                'updated_at' => now()->subDays(2)->setTime(14, 0),
            ],
            [
                'user_type'  => 'App\Models\PesoEmployee',
                'user_id'    => 1,
                'user_name'  => 'Admin PESO',
                'role'       => 'Admin',
                'action'     => 'Status Changed',
                'module'     => 'Applicants',
                'detail'     => 'Applicant Ana Garcia status changed to hired',
                'ip_address' => '192.168.1.1',
                'created_at' => now()->subDays(2)->setTime(15, 45),
                'updated_at' => now()->subDays(2)->setTime(15, 45),
            ],
            [
                'user_type'  => 'App\Models\Employer',
                'user_id'    => 5,
                'user_name'  => 'BDO Unibank',
                'role'       => 'Employer',
                'action'     => 'Status Changed',
                'module'     => 'Applicants',
                'detail'     => 'Applicant Ana Garcia status set to hired for job Accounting Staff',
                'ip_address' => '10.0.0.15',
                'created_at' => now()->subDays(2)->setTime(16, 0),
                'updated_at' => now()->subDays(2)->setTime(16, 0),
            ],
            [
                'user_type'  => 'App\Models\PesoEmployee',
                'user_id'    => 1,
                'user_name'  => 'Admin PESO',
                'role'       => 'Admin',
                'action'     => 'Exported',
                'module'     => 'Reports',
                'detail'     => 'Generated placement report',
                'ip_address' => '192.168.1.1',
                'created_at' => now()->subDays(3)->setTime(9, 0),
                'updated_at' => now()->subDays(3)->setTime(9, 0),
            ],
            [
                'user_type'  => 'App\Models\PesoEmployee',
                'user_id'    => 1,
                'user_name'  => 'Admin PESO',
                'role'       => 'Admin',
                'action'     => 'Deleted',
                'module'     => 'Applicants',
                'detail'     => 'Applicant test record archived',
                'ip_address' => '192.168.1.1',
                'created_at' => now()->subDays(3)->setTime(10, 30),
                'updated_at' => now()->subDays(3)->setTime(10, 30),
            ],
            [
                'user_type'  => 'App\Models\PesoEmployee',
                'user_id'    => 1,
                'user_name'  => 'Admin PESO',
                'role'       => 'Admin',
                'action'     => 'Updated',
                'module'     => 'Employers',
                'detail'     => 'Employer Manila Electric Company status updated',
                'ip_address' => '192.168.1.1',
                'created_at' => now()->subDays(4)->setTime(11, 0),
                'updated_at' => now()->subDays(4)->setTime(11, 0),
            ],
            [
                'user_type'  => 'App\Models\Employer',
                'user_id'    => 2,
                'user_name'  => 'Jollibee Foods Corporation',
                'role'       => 'Employer',
                'action'     => 'Updated',
                'module'     => 'Job Listings',
                'detail'     => "Job 'Restaurant Crew' updated",
                'ip_address' => '172.16.0.10',
                'created_at' => now()->subDays(4)->setTime(14, 0),
                'updated_at' => now()->subDays(4)->setTime(14, 0),
            ],
            [
                'user_type'  => 'App\Models\PesoEmployee',
                'user_id'    => 1,
                'user_name'  => 'Admin PESO',
                'role'       => 'Admin',
                'action'     => 'Status Changed',
                'module'     => 'Employers',
                'detail'     => 'Employer Philippine Airlines verification rejected. Reason: Incomplete documents',
                'ip_address' => '192.168.1.1',
                'created_at' => now()->subDays(5)->setTime(9, 30),
                'updated_at' => now()->subDays(5)->setTime(9, 30),
            ],
            [
                'user_type'  => 'App\Models\PesoEmployee',
                'user_id'    => 1,
                'user_name'  => 'Admin PESO',
                'role'       => 'Admin',
                'action'     => 'Created',
                'module'     => 'Events',
                'detail'     => "Event 'Interview Skills Workshop' created",
                'ip_address' => '192.168.1.1',
                'created_at' => now()->subDays(5)->setTime(13, 0),
                'updated_at' => now()->subDays(5)->setTime(13, 0),
            ],
            [
                'user_type'  => 'App\Models\PesoEmployee',
                'user_id'    => 1,
                'user_name'  => 'Admin PESO',
                'role'       => 'Admin',
                'action'     => 'Logged In',
                'module'     => 'System',
                'detail'     => 'Admin PESO logged in',
                'ip_address' => '192.168.1.1',
                'created_at' => now()->subDays(7)->setTime(8, 0),
                'updated_at' => now()->subDays(7)->setTime(8, 0),
            ],
        ];

        foreach ($logs as $log) {
            AuditLog::create($log);
        }
    }
}
