<?php

namespace Database\Seeders;

use App\Models\Employer;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class EmployerSeeder extends Seeder
{
    public function run(): void
    {
        $employers = [
            [
                'company_name'        => 'Accenture Philippines',
                'legal_name'          => 'Accenture Inc.',
                'tagline'             => 'Innovation across every dimension',
                'about'               => 'Accenture is a global professional services company with leading capabilities in digital, cloud, and security. We help organizations build their digital core, optimize operations, accelerate revenue growth, and enhance services.',
                'email'               => 'hr@accenture.ph',
                'password'            => Hash::make('password123'),
                'industry'            => 'Information Technology',
                'company_size'        => '10,000+',
                'founded'             => '1989',
                'business_type'       => 'Corporation',
                'tin'                 => '123-456-789-000',
                'city'                => 'Taguig City',
                'address'             => '6750 Ayala Ave, Makati, Metro Manila',
                'website'             => 'https://www.accenture.com/ph-en',
                'contact'             => '+63 2 8888 8888',
                'contact_person'      => 'Maria Santos',
                'first_name'          => 'Maria',
                'last_name'           => 'Santos',
                'contact_role'        => 'HR Manager',
                'perks'               => ['Health Insurance', 'HMO', 'Remote Work', '14th Month Pay', 'Paid Leaves'],
                'email_verified_at'   => now(),
                'status'              => 'active',
                'verification_status' => 'verified',
                'total_hired'         => 45,
            ],
            [
                'company_name'        => 'Jollibee Foods Corporation',
                'legal_name'          => 'Jollibee Foods Corporation',
                'tagline'             => 'Bringing joy to every meal',
                'about'               => 'Jollibee is the largest fast-food chain in the Philippines with over 1,400 stores nationwide. We offer a variety of Filipino-influenced fast-food items and are known for our warm, cheerful service.',
                'email'               => 'careers@jollibee.com.ph',
                'password'            => Hash::make('password123'),
                'industry'            => 'Food & Beverage',
                'company_size'        => '5,000–9,999',
                'founded'             => '1978',
                'business_type'       => 'Corporation',
                'tin'                 => '234-567-890-000',
                'city'                => 'Pasig City',
                'address'             => '10 F Jollibee Plaza, Emerald Ave, Pasig',
                'website'             => 'https://www.jollibee.com.ph',
                'contact'             => '+63 2 8634 1111',
                'contact_person'      => 'Juan Dela Cruz',
                'first_name'          => 'Juan',
                'last_name'           => 'Dela Cruz',
                'contact_role'        => 'Recruitment Officer',
                'perks'               => ['Free Meals', 'Uniform Allowance', 'Service Incentive Leave', 'SSS/PhilHealth/Pag-IBIG'],
                'email_verified_at'   => now(),
                'status'              => 'active',
                'verification_status' => 'verified',
                'total_hired'         => 120,
            ],
            [
                'company_name'        => 'SM Supermalls',
                'legal_name'          => 'SM Prime Holdings, Inc.',
                'tagline'             => 'We\'ve got it all for you',
                'about'               => 'SM Supermalls is the largest chain of shopping malls in the Philippines. We operate malls across the country and provide employment opportunities in retail, food service, and mall operations.',
                'email'               => 'recruitment@smsupermalls.com',
                'password'            => Hash::make('password123'),
                'industry'            => 'Retail/Commerce',
                'company_size'        => '5,000–9,999',
                'founded'             => '1985',
                'business_type'       => 'Corporation',
                'tin'                 => '345-678-901-000',
                'city'                => 'Pasay City',
                'address'             => 'SM Mall of Asia, Pasay City, Metro Manila',
                'website'             => 'https://www.smsupermalls.com',
                'contact'             => '+63 2 8857 8888',
                'contact_person'      => 'Rosa Reyes',
                'first_name'          => 'Rosa',
                'last_name'           => 'Reyes',
                'contact_role'        => 'HR Director',
                'perks'               => ['Employee Discount', 'Health Benefits', 'Annual Bonus', 'Training Programs'],
                'email_verified_at'   => now(),
                'status'              => 'active',
                'verification_status' => 'verified',
                'total_hired'         => 200,
            ],
            [
                'company_name'        => 'Globe Telecom',
                'legal_name'          => 'Globe Telecom, Inc.',
                'tagline'             => 'Connecting the Filipino nation',
                'about'               => 'Globe Telecom is a major telecommunications provider in the Philippines. We provide mobile, broadband, and enterprise solutions to millions of customers nationwide.',
                'email'               => 'jobs@globe.com.ph',
                'password'            => Hash::make('password123'),
                'industry'            => 'Telecommunications',
                'company_size'        => '1,000–4,999',
                'founded'             => '1935',
                'business_type'       => 'Corporation',
                'tin'                 => '456-789-012-000',
                'city'                => 'Taguig City',
                'address'             => 'The Globe Tower, 32nd St., BGC, Taguig',
                'website'             => 'https://www.globe.com.ph',
                'contact'             => '+63 2 7730 1000',
                'contact_person'      => 'Carlos Martinez',
                'first_name'          => 'Carlos',
                'last_name'           => 'Martinez',
                'contact_role'        => 'Talent Acquisition Lead',
                'perks'               => ['Free Mobile Data', 'HMO', 'Stock Options', 'Flexible Work'],
                'email_verified_at'   => now(),
                'status'              => 'active',
                'verification_status' => 'verified',
                'total_hired'         => 78,
            ],
            [
                'company_name'        => 'BDO Unibank',
                'legal_name'          => 'BDO Unibank, Inc.',
                'tagline'             => 'We find ways',
                'about'               => 'BDO Unibank is the largest bank in the Philippines in terms of total assets, loans, deposits, and trust funds under management. We serve over 9 million clients nationwide.',
                'email'               => 'hr@bdo.com.ph',
                'password'            => Hash::make('password123'),
                'industry'            => 'Finance/Banking',
                'company_size'        => '5,000–9,999',
                'founded'             => '1968',
                'business_type'       => 'Corporation',
                'tin'                 => '567-890-123-000',
                'city'                => 'Mandaluyong City',
                'address'             => 'BDO Corporate Center, 7899 Makati Ave, Makati',
                'website'             => 'https://www.bdo.com.ph',
                'contact'             => '+63 2 8631 8000',
                'contact_person'      => 'Ana Garcia',
                'first_name'          => 'Ana',
                'last_name'           => 'Garcia',
                'contact_role'        => 'HR Business Partner',
                'perks'               => ['Retirement Plan', 'HMO', 'Annual Leave', 'Performance Bonus'],
                'email_verified_at'   => now(),
                'status'              => 'active',
                'verification_status' => 'verified',
                'total_hired'         => 95,
            ],
            [
                'company_name'        => 'Ayala Land',
                'legal_name'          => 'Ayala Land, Inc.',
                'tagline'             => 'Shaping sustainable communities',
                'about'               => 'Ayala Land is the real estate arm of the Ayala Corporation. We develop residential, commercial, and mixed-use properties across the Philippines.',
                'email'               => 'careers@ayalaland.com.ph',
                'password'            => Hash::make('password123'),
                'industry'            => 'Construction',
                'company_size'        => '1,000–4,999',
                'founded'             => '1988',
                'business_type'       => 'Corporation',
                'tin'                 => '678-901-234-000',
                'city'                => 'Makati City',
                'address'             => '31F Tower One and Exchange Plaza, Ayala Triangle, Makati',
                'website'             => 'https://www.ayalaland.com.ph',
                'contact'             => '+63 2 8908 8888',
                'contact_person'      => 'Pedro Gomez',
                'first_name'          => 'Pedro',
                'last_name'           => 'Gomez',
                'contact_role'        => 'Recruitment Manager',
                'perks'               => ['Housing Allowance', 'Car Plan', 'HMO', 'Rice Allowance'],
                'email_verified_at'   => now(),
                'status'              => 'active',
                'verification_status' => 'verified',
                'total_hired'         => 62,
            ],
            [
                'company_name'        => 'Manila Electric Company',
                'legal_name'          => 'Manila Electric Company',
                'tagline'             => 'Powering communities, energizing lives',
                'about'               => 'Meralco is the largest electric distribution utility in the Philippines. We distribute electricity to Metro Manila and surrounding provinces, serving over 6.6 million customers.',
                'email'               => 'recruitment@meralco.com.ph',
                'password'            => Hash::make('password123'),
                'industry'            => 'Government',
                'company_size'        => '1,000–4,999',
                'founded'             => '1903',
                'business_type'       => 'Corporation',
                'tin'                 => '789-012-345-000',
                'city'                => 'Pasig City',
                'address'             => 'Lopez Building, Meralco Ave, Pasig City',
                'website'             => 'https://www.meralco.com.ph',
                'contact'             => '+63 2 16211',
                'contact_person'      => 'Linda Torres',
                'first_name'          => 'Linda',
                'last_name'           => 'Torres',
                'contact_role'        => 'HR Specialist',
                'perks'               => ['Electricity Subsidy', 'HMO', 'Pension Plan'],
                'email_verified_at'   => null,
                'status'              => 'pending',
                'verification_status' => 'pending',
                'biz_permit_url'      => null,
                'total_hired'         => 0,
            ],
            [
                'company_name'        => 'Philippine Airlines',
                'legal_name'          => 'PAL Holdings, Inc.',
                'tagline'             => 'Heart of the Filipino',
                'about'               => 'Philippine Airlines is the flag carrier of the Philippines and Asia\'s first commercial airline. We connect Manila and key Philippine cities to major international destinations.',
                'email'               => 'jobs@pal.com.ph',
                'password'            => Hash::make('password123'),
                'industry'            => 'Manufacturing',
                'company_size'        => '1,000–4,999',
                'founded'             => '1941',
                'business_type'       => 'Corporation',
                'tin'                 => '890-123-456-000',
                'city'                => 'Pasay City',
                'address'             => 'PAL Center, Legaspi St., Pasay City',
                'website'             => 'https://www.philippineairlines.com',
                'contact'             => '+63 2 8855 8888',
                'contact_person'      => 'Roberto Cruz',
                'first_name'          => 'Roberto',
                'last_name'           => 'Cruz',
                'contact_role'        => 'Talent Acquisition Manager',
                'perks'               => ['Flight Benefits', 'HMO', 'Uniform Allowance'],
                'email_verified_at'   => now(),
                'status'              => 'inactive',
                'verification_status' => 'rejected',
                'remarks'             => 'Incomplete documentation submitted. BIR Certificate missing. Please resubmit.',
                'total_hired'         => 34,
            ],
            [
                'company_name'        => 'Cagayan Valley Medical Center',
                'legal_name'          => 'Cagayan Valley Medical Center',
                'tagline'             => 'Caring for the Cagayan Valley Region',
                'about'               => 'CVMC is a government hospital serving Region 2. We are hiring healthcare professionals including nurses, medical technologists, and administrative staff.',
                'email'               => 'hrd@cvmc.doh.gov.ph',
                'password'            => Hash::make('password123'),
                'industry'            => 'Healthcare',
                'company_size'        => '500–999',
                'founded'             => '1942',
                'business_type'       => 'Government',
                'tin'                 => '901-234-567-000',
                'city'                => 'Tuguegarao City',
                'address'             => 'Tuguegarao City, Cagayan Valley',
                'website'             => 'https://cvmc.doh.gov.ph',
                'contact'             => '+63 78 846 1111',
                'contact_person'      => 'Dr. Marites Reyes',
                'first_name'          => 'Marites',
                'last_name'           => 'Reyes',
                'contact_role'        => 'Chief, Human Resource',
                'perks'               => ['Government Benefits', 'GSIS', 'PhilHealth', 'Annual Leave'],
                'email_verified_at'   => null,
                'status'              => 'pending',
                'verification_status' => 'pending',
                'total_hired'         => 0,
            ],
            [
                'company_name'        => 'Isabela State University',
                'legal_name'          => 'Isabela State University',
                'tagline'             => 'Excellence, Service, Integrity',
                'about'               => 'ISU is a state university in Region 2. We are hiring instructors, administrative staff, and technical personnel for our campuses across Isabela.',
                'email'               => 'hrm@isu.edu.ph',
                'password'            => Hash::make('password123'),
                'industry'            => 'Education',
                'company_size'        => '500–999',
                'founded'             => '1978',
                'business_type'       => 'Government',
                'tin'                 => '012-345-678-000',
                'city'                => 'Echague, Isabela',
                'address'             => 'San Fabian, Echague, Isabela',
                'website'             => 'https://www.isu.edu.ph',
                'contact'             => '+63 78 682 2425',
                'contact_person'      => 'Dr. Lorenzo Santos',
                'first_name'          => 'Lorenzo',
                'last_name'           => 'Santos',
                'contact_role'        => 'HRM Director',
                'perks'               => ['Government Benefits', 'Research Grants', 'Study Leave'],
                'email_verified_at'   => now(),
                'status'              => 'active',
                'verification_status' => 'verified',
                'total_hired'         => 28,
            ],
        ];

        foreach ($employers as $employer) {
            Employer::firstOrCreate(
                ['email' => $employer['email']],
                $employer
            );
        }
    }
}
