<?php

namespace Database\Seeders;

use App\Models\JobListing;
use Illuminate\Database\Seeder;

class JobListingSeeder extends Seeder
{
    public function run(): void
    {
        // Seed a rich mix of jobs (full-time, part-time, contract, freelance)
        // that align with the categories used in the Flutter filter UI.
        JobListing::truncate();

        $jobs = [
            [
                'title'            => 'Software Developer',
                'company'          => 'Tech Solutions Inc.',
                'company_initial'  => 'T',
                'company_color'    => '3B82F6',
                'location'         => 'Santiago City, Isabela',
                'description'      => 'Looking for a skilled software developer with experience in mobile and web development. You will be working on cutting-edge projects and collaborating with a talented team.',
                'requirements'     => [
                    "Bachelor's degree in Computer Science or related field",
                    'Proficiency in JavaScript, Python, or Java',
                    'Experience with web frameworks (React, Angular, or Vue)',
                    'Strong problem-solving skills',
                    'Good communication skills',
                ],
                'skills'           => ['Flutter', 'Laravel', 'MySQL'],
                'experience_level' => '2-3 years experience',
                'salary_min'       => '₱25,000',
                'salary_max'       => '₱35,000',
                'employment_type'  => 'Full-time',
                'category'         => 'IT & Software',
                'match_percentage' => 95,
                'is_urgent'        => true,
                'created_at'       => now()->subDays(2),
            ],
            [
                'title'            => 'Administrative Assistant',
                'company'          => 'City Government',
                'company_initial'  => 'C',
                'company_color'    => '10B981',
                'location'         => 'Santiago City, Isabela',
                'description'      => 'The City Government is seeking a reliable Administrative Assistant to provide support to our department. Duties include managing schedules, handling correspondence, and maintaining office records.',
                'requirements'     => [
                    "Bachelor's degree in any field",
                    'Proficient in MS Office applications',
                    'Excellent organizational skills',
                    'Strong written and verbal communication',
                    'Attention to detail',
                ],
                'skills'           => ['MS Office', 'Communication', 'Filing'],
                'experience_level' => '1-2 years experience',
                'salary_min'       => '₱18,000',
                'salary_max'       => '₱22,000',
                'employment_type'  => 'Full-time',
                'category'         => 'Sales & Marketing',
                'match_percentage' => 82,
                'is_urgent'        => false,
                'created_at'       => now()->subDays(3),
            ],
            [
                'title'            => 'Sales Representative',
                'company'          => 'PhilMart Trading',
                'company_initial'  => 'P',
                'company_color'    => 'F59E0B',
                'location'         => 'Santiago City, Isabela',
                'description'      => 'Join our dynamic sales team! We are looking for motivated individuals to promote and sell our products. Commission-based incentives available for top performers.',
                'requirements'     => [
                    'High school diploma or equivalent',
                    'Excellent communication and interpersonal skills',
                    'Self-motivated and goal-oriented',
                    'Willing to do field work',
                    'With valid driver\'s license (preferred)',
                ],
                'skills'           => ['Sales', 'Negotiation', 'Customer Service'],
                'experience_level' => 'Entry level',
                'salary_min'       => '₱15,000',
                'salary_max'       => '₱20,000',
                'employment_type'  => 'Full-time',
                'category'         => 'Sales & Marketing',
                'match_percentage' => 78,
                'is_urgent'        => true,
                'created_at'       => now()->subDays(1),
            ],
            [
                'title'            => 'Registered Nurse',
                'company'          => 'Santiago Medical Center',
                'company_initial'  => 'S',
                'company_color'    => 'EF4444',
                'location'         => 'Santiago City, Isabela',
                'description'      => 'We are hiring compassionate and skilled Registered Nurses to provide quality patient care. Must be willing to work in shifts and handle emergency situations.',
                'requirements'     => [
                    "Bachelor's degree in Nursing",
                    'Valid PRC License',
                    'BLS/ACLS certification',
                    'Good interpersonal skills',
                    'Willing to work on shifting schedule',
                ],
                'skills'           => ['Patient Care', 'BLS', 'Medical Records'],
                'experience_level' => '1 year hospital experience',
                'salary_min'       => '₱20,000',
                'salary_max'       => '₱28,000',
                'employment_type'  => 'Full-time',
                'category'         => 'Healthcare',
                'match_percentage' => 88,
                'is_urgent'        => false,
                'created_at'       => now()->subDays(5),
            ],
            [
                'title'            => 'Warehouse Staff',
                'company'          => 'Logistics Hub Corp.',
                'company_initial'  => 'L',
                'company_color'    => '8B5CF6',
                'location'         => 'Santiago City, Isabela',
                'description'      => 'Looking for hardworking warehouse staff to handle inventory management, packing, and shipping operations. Physical fitness required.',
                'requirements'     => [
                    'High school diploma',
                    'Physically fit',
                    'Can lift heavy objects',
                    'Basic computer literacy',
                    'Team player',
                ],
                'skills'           => ['Inventory', 'Logistics', 'Forklift'],
                'experience_level' => 'No experience required',
                'salary_min'       => '₱12,000',
                'salary_max'       => '₱15,000',
                'employment_type'  => 'Full-time',
                'category'         => 'Manufacturing',
                'match_percentage' => 70,
                'is_urgent'        => true,
                'created_at'       => now(),
            ],
            [
                'title'            => 'Cashier',
                'company'          => 'SM SaveMore Market',
                'company_initial'  => 'S',
                'company_color'    => '0EA5E9',
                'location'         => 'Santiago City, Isabela',
                'description'      => 'We are looking for a friendly and efficient Cashier to join our team. You will handle customer transactions, maintain accurate cash counts, and provide excellent service.',
                'requirements'     => [
                    'High school diploma or equivalent',
                    'Basic math proficiency',
                    'Customer service skills',
                    'Honest and trustworthy',
                    'Can work in shifting schedule',
                ],
                'skills'           => ['Cashiering', 'Customer Service', 'POS System'],
                'experience_level' => 'No experience required',
                'salary_min'       => '₱12,000',
                'salary_max'       => '₱15,000',
                'employment_type'  => 'Full-time',
                'category'         => 'Sales & Marketing',
                'match_percentage' => 74,
                'is_urgent'        => false,
                'created_at'       => now()->subDays(6),
            ],
            [
                'title'            => 'Sales Associate',
                'company'          => 'Robinsons Department Store',
                'company_initial'  => 'R',
                'company_color'    => 'EC4899',
                'location'         => 'Santiago City, Isabela',
                'description'      => 'Join our retail team as a Sales Associate! You will assist customers in finding products, manage merchandise displays, and process transactions with a smile.',
                'requirements'     => [
                    'High school diploma or equivalent',
                    'Good communication skills',
                    'Presentable and customer-oriented',
                    'Willing to work on weekends and holidays',
                    'Energetic and team player',
                ],
                'skills'           => ['Retail Sales', 'Customer Service', 'Merchandising'],
                'experience_level' => 'Entry level',
                'salary_min'       => '₱13,000',
                'salary_max'       => '₱16,000',
                'employment_type'  => 'Full-time',
                'category'         => 'Sales & Marketing',
                'match_percentage' => 68,
                'is_urgent'        => false,
                'created_at'       => now()->subDays(11),
            ],

            // Part‑time (3)
            [
                'title'            => 'Part-time Tutor',
                'company'          => 'Bright Minds Tutorial Center',
                'company_initial'  => 'B',
                'company_color'    => '6366F1',
                'location'         => 'Santiago City, Isabela',
                'description'      => 'Provide after-school tutoring for junior and senior high school students in Math and Science subjects.',
                'requirements'     => [
                    'At least 2nd year college or graduate in related course',
                    'Strong foundation in Math and Science',
                    'Good communication skills',
                ],
                'skills'           => ['Teaching', 'Tutoring', 'Communication'],
                'experience_level' => 'Entry level',
                'salary_min'       => '₱150 / hour',
                'salary_max'       => '₱200 / hour',
                'employment_type'  => 'Part-time',
                'category'         => 'Education',
                'match_percentage' => 80,
                'is_urgent'        => true,
                'created_at'       => now()->subDays(3),
            ],
            [
                'title'            => 'Part-time Clinic Assistant',
                'company'          => 'Santiago Family Clinic',
                'company_initial'  => 'F',
                'company_color'    => '22C55E',
                'location'         => 'Santiago City, Isabela',
                'description'      => 'Assist nurses and doctors in a small outpatient clinic during peak hours.',
                'requirements'     => [
                    'At least senior high graduate',
                    'With basic knowledge of vital signs is an advantage',
                    'Customer-oriented and approachable',
                ],
                'skills'           => ['Customer Service', 'Basic Nursing Aid'],
                'experience_level' => 'No experience required',
                'salary_min'       => '₱6,000',
                'salary_max'       => '₱8,000',
                'employment_type'  => 'Part-time',
                'category'         => 'Healthcare',
                'match_percentage' => 72,
                'is_urgent'        => false,
                'created_at'       => now()->subDays(4),
            ],
            [
                'title'            => 'Part-time Sales Promoter',
                'company'          => 'Gadget Hub',
                'company_initial'  => 'G',
                'company_color'    => '0EA5E9',
                'location'         => 'Santiago City, Isabela',
                'description'      => 'Promote electronic gadgets and assist customers during weekends and holidays.',
                'requirements'     => [
                    'Senior high graduate',
                    'Tech-savvy and updated with latest gadgets',
                    'Willing to work on weekends and holidays',
                ],
                'skills'           => ['Sales', 'Customer Service'],
                'experience_level' => 'Entry level',
                'salary_min'       => '₱200 / day + commission',
                'salary_max'       => '₱400 / day + commission',
                'employment_type'  => 'Part-time',
                'category'         => 'Sales & Marketing',
                'match_percentage' => 76,
                'is_urgent'        => true,
                'created_at'       => now()->subDays(1),
            ],

            // Contract (3)
            [
                'title'            => 'IT Support Technician (Contract)',
                'company'          => 'North Valley College',
                'company_initial'  => 'N',
                'company_color'    => '3B82F6',
                'location'         => 'Santiago City, Isabela',
                'description'      => 'Provide on-site IT support for computer laboratories and offices for a 6-month contract.',
                'requirements'     => [
                    'Graduate of IT or related course',
                    'Knowledge in basic networking and hardware troubleshooting',
                    'Willing to work on shifting schedule',
                ],
                'skills'           => ['Technical Support', 'Networking', 'Hardware Repair'],
                'experience_level' => '1 year experience',
                'salary_min'       => '₱20,000',
                'salary_max'       => '₱25,000',
                'employment_type'  => 'Contract',
                'category'         => 'IT & Software',
                'match_percentage' => 84,
                'is_urgent'        => true,
                'created_at'       => now()->subDays(7),
            ],
            [
                'title'            => 'Construction Site Engineer (Contract)',
                'company'          => 'Isabela Builders Corp.',
                'company_initial'  => 'I',
                'company_color'    => 'F97316',
                'location'         => 'Santiago City, Isabela',
                'description'      => 'Monitor ongoing construction projects and coordinate with foremen for a 1-year contract.',
                'requirements'     => [
                    'Licensed Civil Engineer',
                    'With at least 1 year site experience',
                    'Can work under pressure and with minimal supervision',
                ],
                'skills'           => ['Project Monitoring', 'AutoCAD', 'Site Supervision'],
                'experience_level' => '1-3 years experience',
                'salary_min'       => '₱30,000',
                'salary_max'       => '₱40,000',
                'employment_type'  => 'Contract',
                'category'         => 'Construction',
                'match_percentage' => 90,
                'is_urgent'        => false,
                'created_at'       => now()->subDays(10),
            ],
            [
                'title'            => 'Data Encoder (Contract)',
                'company'          => 'Santiago Manufacturing Corp.',
                'company_initial'  => 'M',
                'company_color'    => '22C55E',
                'location'         => 'Santiago City, Isabela',
                'description'      => 'Encode production and inventory data to the company system for a 6-month contract.',
                'requirements'     => [
                    'Senior high graduate or college level',
                    'Fast and accurate typing skills',
                    'Basic knowledge in MS Excel',
                ],
                'skills'           => ['Data Entry', 'MS Excel'],
                'experience_level' => 'Entry level',
                'salary_min'       => '₱14,000',
                'salary_max'       => '₱16,000',
                'employment_type'  => 'Contract',
                'category'         => 'Manufacturing',
                'match_percentage' => 79,
                'is_urgent'        => true,
                'created_at'       => now()->subDays(8),
            ],

            // Freelance (3)
            [
                'title'            => 'Freelance Graphic Designer',
                'company'          => 'Local Brands Collective',
                'company_initial'  => 'L',
                'company_color'    => 'EC4899',
                'location'         => 'Remote / Santiago City, Isabela',
                'description'      => 'Create marketing materials and social media graphics for small local businesses on a per-project basis.',
                'requirements'     => [
                    'Portfolio of previous graphic design work',
                    'Knowledge in Photoshop or Canva',
                    'Creative and detail-oriented',
                ],
                'skills'           => ['Graphic Design', 'Branding', 'Social Media'],
                'experience_level' => '1-2 years experience',
                'salary_min'       => '₱5,000 / project',
                'salary_max'       => '₱15,000 / project',
                'employment_type'  => 'Freelance',
                'category'         => 'Sales & Marketing',
                'match_percentage' => 86,
                'is_urgent'        => false,
                'created_at'       => now()->subDays(9),
            ],
            [
                'title'            => 'Freelance Web Developer',
                'company'          => 'Digital Peso Solutions',
                'company_initial'  => 'D',
                'company_color'    => '4F46E5',
                'location'         => 'Remote',
                'description'      => 'Develop and maintain simple websites for local businesses on a freelance basis.',
                'requirements'     => [
                    'Experience in HTML, CSS, and JavaScript',
                    'Knowledge in any PHP or JS framework is a plus',
                    'Can meet deadlines and communicate clearly',
                ],
                'skills'           => ['Web Development', 'HTML/CSS', 'JavaScript'],
                'experience_level' => '1-3 years experience',
                'salary_min'       => '₱10,000 / project',
                'salary_max'       => '₱25,000 / project',
                'employment_type'  => 'Freelance',
                'category'         => 'IT & Software',
                'match_percentage' => 92,
                'is_urgent'        => true,
                'created_at'       => now()->subDays(12),
            ],
            [
                'title'            => 'Freelance Content Writer',
                'company'          => 'Isabela Online Media',
                'company_initial'  => 'I',
                'company_color'    => 'F97316',
                'location'         => 'Remote',
                'description'      => 'Write blog posts and social media captions about local news, events, and career tips.',
                'requirements'     => [
                    'Strong writing skills in English and Filipino',
                    'Can research and write original content',
                    'Able to submit work on time',
                ],
                'skills'           => ['Content Writing', 'Research', 'SEO (basic)'],
                'experience_level' => 'Entry level',
                'salary_min'       => '₱500 / article',
                'salary_max'       => '₱1,500 / article',
                'employment_type'  => 'Freelance',
                'category'         => 'Education',
                'match_percentage' => 83,
                'is_urgent'        => false,
                'created_at'       => now()->subDays(6),
            ],
        ];

        foreach ($jobs as $job) {
            JobListing::create($job);
        }
    }
}
