<?php

namespace Database\Seeders;

use App\Models\ApplicantDocument;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    public function run(): void
    {
        $users = [
            [
                'name'        => 'Maria Santos',
                'email'       => 'maria.santos@email.com',
                'password'    => Hash::make('password'),
                'age'         => 24,
                'gender'      => 'Female',
                'phone'       => '09171234567',
                'address'     => 'Brgy. Villasis, Santiago City, Isabela',
                'skills'      => ['Laravel', 'Vue.js', 'MySQL', 'PHP', 'JavaScript'],
                'peso_status' => 'placed',
                'education'   => "Bachelor of Science in Information Technology\nIsabela State University – Santiago Campus (2022)",
                'experience'  => "Junior Web Developer – Tech Solutions Inc. (2022–2023)\nFreelance WordPress Developer (2021–2022)",
                'notes'       => 'Strong candidate. Placed at Accenture Philippines as Junior Developer.',
            ],
            [
                'name'        => 'Juan dela Cruz',
                'email'       => 'juan.delacruz@email.com',
                'password'    => Hash::make('password'),
                'age'         => 28,
                'gender'      => 'Male',
                'phone'       => '09189876543',
                'address'     => 'Brgy. Centro East, Santiago City, Isabela',
                'skills'      => ['Customer Service', 'Sales', 'MS Office', 'Communication'],
                'peso_status' => 'processing',
                'education'   => "Bachelor of Science in Business Administration\nSantiago City Polytechnic College (2019)",
                'experience'  => "Sales Associate – SM Supermalls (2019–2022)\nCustomer Service Rep – BPO Company (2022–2023)",
                'notes'       => 'Applied for sales positions. Currently being interviewed by Globe Telecom.',
            ],
            [
                'name'        => 'Ana Garcia',
                'email'       => 'ana.garcia@email.com',
                'password'    => Hash::make('password'),
                'age'         => 22,
                'gender'      => 'Female',
                'phone'       => '09201122334',
                'address'     => 'Brgy. Dubinan West, Santiago City, Isabela',
                'skills'      => ['Accounting', 'Bookkeeping', 'MS Excel', 'QuickBooks', 'Taxation'],
                'peso_status' => 'hired',
                'education'   => "Bachelor of Science in Accountancy\nIsabela State University – Santiago Campus (2023)",
                'experience'  => "OJT – BDO Unibank Santiago Branch (2022)\nBookkeeper – Family Business (2021–2022)",
                'notes'       => 'Hired by BDO as Junior Accountant. Success story.',
            ],
            [
                'name'        => 'Pedro Reyes',
                'email'       => 'pedro.reyes@email.com',
                'password'    => Hash::make('password'),
                'age'         => 35,
                'gender'      => 'Male',
                'phone'       => '09155566778',
                'address'     => 'Brgy. Calaocan District, Santiago City, Isabela',
                'skills'      => ['Electrical Works', 'Plumbing', 'Construction', 'Carpentry'],
                'peso_status' => 'processing',
                'education'   => "TESDA NC II – Electrical Installation & Maintenance (2018)",
                'experience'  => "Electrician – Freelance (2018–present)\nConstruction Worker – Ayala Land Project (2020–2021)",
                'notes'       => 'Skilled tradesman. Referred to Meralco for lineman position.',
            ],
            [
                'name'        => 'Rosa Mendoza',
                'email'       => 'rosa.mendoza@email.com',
                'password'    => Hash::make('password'),
                'age'         => 26,
                'gender'      => 'Female',
                'phone'       => '09278899001',
                'address'     => 'Brgy. Plaridel, Santiago City, Isabela',
                'skills'      => ['Food Service', 'Cashiering', 'Inventory', 'Customer Service'],
                'peso_status' => 'hired',
                'education'   => "Senior High School – TVL Track – Food & Beverage (2019)",
                'experience'  => "Crew Member – Jollibee (2019–2021)\nShift Supervisor – 7-Eleven (2021–2023)",
                'notes'       => 'Hired by Jollibee Foods Corp. as assistant store manager.',
            ],
            [
                'name'        => 'Carlos Bautista',
                'email'       => 'carlos.bautista@email.com',
                'password'    => Hash::make('password'),
                'age'         => 30,
                'gender'      => 'Male',
                'phone'       => '09339012345',
                'address'     => 'Brgy. Malvar, Santiago City, Isabela',
                'skills'      => ['Network Administration', 'Cybersecurity', 'Linux', 'Python', 'SQL'],
                'peso_status' => 'placed',
                'education'   => "Bachelor of Science in Computer Engineering\nCagayan State University (2017)",
                'experience'  => "Network Admin – Globe Telecom (2017–2021)\nIT Support Specialist – Various (2021–2023)",
                'notes'       => 'Experienced IT professional. Placed at Globe Telecom as Senior Network Administrator.',
            ],
            [
                'name'        => 'Liza Fernandez',
                'email'       => 'liza.fernandez@email.com',
                'password'    => Hash::make('password'),
                'age'         => 29,
                'gender'      => 'Female',
                'phone'       => '09451234560',
                'address'     => 'Brgy. Nabbuan, Santiago City, Isabela',
                'skills'      => ['Teaching', 'Curriculum Development', 'Public Speaking', 'MS Office'],
                'peso_status' => 'processing',
                'education'   => "Bachelor of Elementary Education\nIsabela State University (2018)",
                'experience'  => "Teacher – Private School (2018–2022)\nTutor – Freelance (2022–present)",
                'notes'       => 'Looking for teaching position in public school.',
            ],
            [
                'name'        => 'Mark Villanueva',
                'email'       => 'mark.villanueva@email.com',
                'password'    => Hash::make('password'),
                'age'         => 23,
                'gender'      => 'Male',
                'phone'       => '09567891234',
                'address'     => 'Brgy. Divisoria, Santiago City, Isabela',
                'skills'      => ['Graphic Design', 'Adobe Photoshop', 'Illustrator', 'Canva', 'Social Media'],
                'peso_status' => 'rejected',
                'education'   => "Bachelor of Fine Arts – Major in Visual Communication\nSantiago City Polytechnic College (2023)",
                'experience'  => "Freelance Graphic Designer (2021–present)",
                'notes'       => 'Mismatch in expected salary. Reapplied for different position.',
            ],
            [
                'name'        => 'Elena Cruz',
                'email'       => 'elena.cruz@email.com',
                'password'    => Hash::make('password'),
                'age'         => 32,
                'gender'      => 'Female',
                'phone'       => '09198765432',
                'address'     => 'Brgy. Balintocatoc, Santiago City, Isabela',
                'skills'      => ['Nursing', 'Patient Care', 'First Aid', 'Medical Records', 'BLS'],
                'peso_status' => 'hired',
                'education'   => "Bachelor of Science in Nursing\nIsabela Medical Center College (2015)\nPRC Licensed Nurse (2015)",
                'experience'  => "Staff Nurse – Santiago City General Hospital (2015–2023)",
                'notes'       => 'Experienced nurse. Hired at private clinic. Also referred to DOLE overseas placement.',
            ],
            [
                'name'        => 'Roberto Tan',
                'email'       => 'roberto.tan@email.com',
                'password'    => Hash::make('password'),
                'age'         => 27,
                'gender'      => 'Male',
                'phone'       => '09384567890',
                'address'     => 'Brgy. Mabini, Santiago City, Isabela',
                'skills'      => ['Driving', 'Heavy Equipment Operation', 'Delivery', 'Logistics'],
                'peso_status' => 'processing',
                'education'   => "Senior High School – ABM Strand (2019)\nProfessional Driver's License (2020)",
                'experience'  => "Driver – Delivery Company (2020–2023)",
                'notes'       => 'Good driving record. Being coordinated with logistics firms.',
            ],
            [
                'name'        => 'Jenny Pascual',
                'email'       => 'jenny.pascual@email.com',
                'password'    => Hash::make('password'),
                'age'         => 25,
                'gender'      => 'Female',
                'phone'       => '09112233445',
                'address'     => 'Brgy. Rosario, Santiago City, Isabela',
                'skills'      => ['Social Work', 'Community Development', 'Data Entry', 'MS Office'],
                'peso_status' => 'placed',
                'education'   => "Bachelor of Science in Social Work\nIsabela State University (2022)",
                'experience'  => "OJT – DSWD Regional Office (2021)\nCommunity Volunteer (2022–2023)",
                'notes'       => 'Placed at DSWD as social welfare assistant.',
            ],
            [
                'name'        => 'Dennis Agustin',
                'email'       => 'dennis.agustin@email.com',
                'password'    => Hash::make('password'),
                'age'         => 31,
                'gender'      => 'Male',
                'phone'       => '09223344556',
                'address'     => 'Brgy. Sagunto, Santiago City, Isabela',
                'skills'      => ['Welding', 'Fabrication', 'Metal Works', 'Safety Protocols'],
                'peso_status' => 'processing',
                'education'   => "TESDA NC II – Shielded Metal Arc Welding (2016)",
                'experience'  => "Welder – Construction Firm (2016–2022)\nWelding Supervisor – Fabrication Shop (2022–2023)",
                'notes'       => 'Highly skilled welder. Endorsed to construction projects.',
            ],
        ];

        foreach ($users as $userData) {
            User::firstOrCreate(
                ['email' => $userData['email']],
                $userData
            );
        }
    }
}
